### ISSUE TITLE
reports/m1_proposal.md - Section 1: Motivation and Purpose

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/DSCI-532_2024_16_SilentEpidemic#11]
rubric={reasoning:12}

In a few sentences, provide motivation for why you are creating a dashboard:

Who is your target audience, and what role are you embodying?
What is the problem the target audience is facing and why is it important to solve?
How can your dashboard assist in solving this problem for the intended target audience?
You can read the [Project background](https://github.ubc.ca/MDS-2023-24/DSCI_532_milestone1_group16/blob/master/milestone1.md#project-background) section for some rough ideas. Be brief and clear. Example writeup:

Our role: Data scientist consultancy firm

Target audience: Health care administrators

Missed medical appointments cost the healthcare system a lot of money and affects the quality of care. If we could understand which factors lead to missed appointments it may be possible to reduce their frequency and use the saved resources to improve patient outcomes. To address this challenge, we propose building a data visualization app that allows health care administrators to visually explore a dataset of missed appointments to identify common factors. Our app will show the distribution of factors contributing to appointment show/no show and allow users to explore different aspects of this data by filtering and re-ordering on different variables in order to compare factors that contribute to absence.

**Comment by billwan96** [comment]
### 1. Target Audience & Your Role:
**Our Role**: Researchers at the National Institute on Drug Abuse (NIDA)
**Target Audience**: Dr. Linda Darling, State Board President, California State Board of Education

### 2. Problem & Importance:
Dr. Darling and our group are concerned about the alarming rise in national drug overdose deaths and want to provide additional education for upper high school students. This is crucial because:
- Drug overdose deaths involving synthetic opioids like fentanyl have increased significantly in recent years (https://www.cnn.com/2022/03/16/health/overdose-deaths-record-high-fentanyl/index.html)
-  Many overdoses are unintentional, often occurring because people underestimate the dangers of mixing drugs (https://www.yalemedicine.org/news/fentanyl-driving-overdoses)
- Effective education programs can equip students with the knowledge and skills to identify the risks of different drugs and recognize the signs and symptoms of overdose. (https://www.samhsa.gov/sites/default/files/factsheet_educator_what_educators_can_do.pdf)

### 3. How Our Dashboard Helps:
Our dashboard would be able to picture the following:
- Overdose Trends: Show a clear upward trend in national drug overdose deaths over time, particularly focusing on the rise in synthetic opioid-related deaths.
- Drug Risk Comparisons: Visually represent the relative risks associated with different drug categories, highlighting the dangers of synthetic opioids compared to other substances.
- Demographic Disparities: Highlight potential risk factors by ethnicity and gender to identify high-risk student populations.

**Comment by AlysenTownsley** [comment]
Thanks Bill - great job including relevant sources.
